server.port: ${PORT:8080}

app.param.base.currency: ${BASE_CURRENCY:USD}
app.param.local.currency: RUB

app.param.search.rich: rich
app.param.search.broke: broke

app.param.url.error: img/giphy.webp
app.param.url.rich: img/giphy_rich.gif
app.param.url.broke: img/giphy_broke.webp

feign.client.config.default.connectTimeout: 5000
feign.client.config.default.readTimeout: 5000
feign.client.config.default.loggerLevel: basic

org.openexchangerates.app_id: ${EXCHANGE_API_ID}
org.openexchengerates.url: ${EXCHANGE_URL:https://openexchangerates.org/api}

com.giphy.developers.app_key: ${GIPHY_API_KEY}
com.giphy.developers.url: ${GIPHY_URL:https://api.giphy.com/v1/gifs}